accounts:
  - name: alice
    coins: ["100000000uatom", "100000000000000000000amjt"]
  - name: bob
    coins: ["5000000000000amjt"]
validator:
  name: alice
  staked: "100000000000000000000amjt"
faucet:
  name: bob
  coins: ["10amjt"]
build:
  binary: "mjtd"
init:
  home: "$HOME/.mjtd"
  app:
    evm-rpc:
      address: "0.0.0.0:8545" # change the JSON-RPC address and port
      ws-address: "0.0.0.0:8546" # change the JSON-RPC websocket address and port
genesis:
  chain_id: "mjtd_9000-1"
  app_state:
    staking:
      params:
        bond_denom: "amjt"
    mint:
      params:
        mint_denom: "amjt"
    crisis:
      constant_fee:
        denom: "amjt"
    gov:
      deposit_params:
        min_deposit:
          - amount: "10000000"
            denom: "amjt"
    evm:
      params:
        evm_denom: "amjt"
